name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check the code
        run: ls

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build code to Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: irvanrizki225/library-api:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "🚀 Starting deployment on EC2..."
          docker system prune -a -f
          cd ~/app
          git pull origin main
          docker pull irvanrizki225/library-api:${{ github.sha }}
          docker-compose down
          docker volume prune -f  # Bersihkan volume yang bisa menyimpan cache lama
          docker-compose up -d
          echo "✅ Deployment successful!"
